ProjIntegrador/Models/Instalacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjIntegrador.Models
{
    public class Instalacao
    {
        public int InstalacaoId { get; set; }
        public DateTime DataInstalacao { get; set; }
        public string Observacao { get; set; }

        public Endereco Endereco { get; set; }
        public int EnderecoId { get; set; }

        public Instalador Instalador { get; set; }
        public int InstaladorId { get; set; }
        
        public Venda Venda { get; set; }
        public int VendaId { get; set; }


    }
}

ProjIntegrador/Controllers/InstalacaoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjIntegrador.DataAccess;
using ProjIntegrador.Models;

namespace ProjIntegrador.Controllers
{
    public class InstalacaoController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Instalacao
        public ActionResult Index()
        {
            var instalacao = db.Instalacao.Include(i => i.Endereco).Include(i => i.Instalador).Include(i => i.Venda);
            return View(instalacao.ToList());
        }

        // GET: Instalacao/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalacao instalacao = db.Instalacao.Find(id);
            if (instalacao == null)
            {
                return HttpNotFound();
            }
            return View(instalacao);
        }

        // GET: Instalacao/Create
        public ActionResult Create()
        {
            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao");
            ViewBag.InstaladorId = new SelectList(db.Instalador, "InstaladorId", "InstaladorId");
            ViewBag.VendaId = new SelectList(db.Venda, "VendaId", "VendaId");
            return View();
        }

        // POST: Instalacao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InstalacaoId,DataInstalacao,Observacao,EnderecoId,InstaladorId,VendaId")] Instalacao instalacao)
        {
            if (ModelState.IsValid)
            {
                db.Instalacao.Add(instalacao);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao", instalacao.EnderecoId);
            ViewBag.InstaladorId = new SelectList(db.Instalador, "InstaladorId", "InstaladorId", instalacao.InstaladorId);
            ViewBag.VendaId = new SelectList(db.Venda, "VendaId", "VendaId", instalacao.VendaId);
            return View(instalacao);
        }

        // GET: Instalacao/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalacao instalacao = db.Instalacao.Find(id);
            if (instalacao == null)
            {
                return HttpNotFound();
            }
            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao", instalacao.EnderecoId);
            ViewBag.InstaladorId = new SelectList(db.Instalador, "InstaladorId", "InstaladorId", instalacao.InstaladorId);
            ViewBag.VendaId = new SelectList(db.Venda, "VendaId", "VendaId", instalacao.VendaId);
            return View(instalacao);
        }

        // POST: Instalacao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InstalacaoId,DataInstalacao,Observacao,EnderecoId,InstaladorId,VendaId")] Instalacao instalacao)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instalacao).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao", instalacao.EnderecoId);
            ViewBag.InstaladorId = new SelectList(db.Instalador, "InstaladorId", "InstaladorId", instalacao.InstaladorId);
            ViewBag.VendaId = new SelectList(db.Venda, "VendaId", "VendaId", instalacao.VendaId);
            return View(instalacao);
        }

        // GET: Instalacao/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalacao instalacao = db.Instalacao.Find(id);
            if (instalacao == null)
            {
                return HttpNotFound();
            }
            return View(instalacao);
        }

        // POST: Instalacao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instalacao instalacao = db.Instalacao.Find(id);
            db.Instalacao.Remove(instalacao);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjIntegrador/Views/Instalacao/Create.cshtml
@model ProjIntegrador.Models.Instalacao

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalações
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalacao", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Cadastar novo Instalacao
                    </div>
                    <br /><br />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class="control-label col-md-2"> Observação</div>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="control-label col-md-2"> ID do Endereço</div>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.EnderecoId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.EnderecoId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="control-label col-md-2"> ID do Instalador</div>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.InstaladorId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.InstaladorId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="control-label col-md-2"> ID da Venda</div>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.VendaId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.VendaId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-12">
                                    <input type="submit" value="Criar Instalação" class="btn-wide btn btn-success mb-3" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalacao/Delete.cshtml
@model ProjIntegrador.Models.Instalacao

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalações
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalacao", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Deletar Instalação
                    </div>
                    <br />

                    <div style="padding: 0 25px; margin: 10px 0;">
                        <div class="dl-horizontal">
                            <div class="col-md-3">
                                <dt>
                                    Observação
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Observacao)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    ID do Endereço
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.EnderecoId)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    ID do Instalador
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.InstaladorId)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    ID da Venda
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.VendaId)
                                </dd>
                            </div>

                        </div>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Deletar Instalação" class="btn-wide btn btn-success mb-3" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalacao/Details.cshtml
@model ProjIntegrador.Models.Instalacao

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalações
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalacao", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Detalhes da Instalação
                    </div>

                    <div style="padding: 0 25px; margin: 10px 0;">
                        <div class="col-md-3">
                            <dt>
                                Observação
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Observacao)
                            </dd>
                        </div>

                        <div class="col-md-3">
                            <dt>
                                ID do Endereço
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.EnderecoId)
                            </dd>
                        </div>

                        <div class="col-md-3">
                            <dt>
                                ID do Instalador
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.InstaladorId)
                            </dd>
                        </div>

                        <div class="col-md-3">
                            <dt>
                                ID da Venda
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.VendaId)
                            </dd>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalacao/Edit.cshtml
@model ProjIntegrador.Models.Instalacao

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalaçãos
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalacao", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Editar Instalação
                    </div>
                    <br /><br />


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.InstalacaoId)
                    <div class="form-group">
                        <div class="control-label col-md-2"> Observação</div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.Observacao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Observacao, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2"> ID do Endereço</div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.EnderecoId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EnderecoId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2"> ID do Instalador</div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.InstaladorId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.InstaladorId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2"> ID da Venda</div>
                        <div class="col-md-12">
                            @Html.EditorFor(model => model.VendaId, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.VendaId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-12">
                            <input type="submit" value="Editar Instalação" class="btn-wide btn btn-success mb-3    " />
                        </div>
                    </div>
                </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalacao/Index.cshtml
@model IEnumerable<ProjIntegrador.Models.Instalacao>

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalações
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Criar Novo", "Create", "Instalacao", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Instalaçãos Cadastrados
                    </div>
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">Instalação</th>
                                    <th class="text-center">Venda</th>
                                    <th class="text-center">Data</th>
                                    <th class="text-center">Observação</th>
                                    <th class="text-center">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.InstalacaoId)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.VendaId)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.DataInstalacao)
                                        </td>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.Observacao)
                                        </td>
                                        <td class="text-center">
                                            @Html.ActionLink("Edit", "Edit", new { id = item.InstalacaoId }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.InstalacaoId }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.InstalacaoId })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>