ProjIntegrador/Models/Interessado.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjIntegrador.Models
{
    public class Interessado
    {
        public int InteressadoId { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public DateTime DataCadastro { get; set; }
        public DateTime DataAgendamento { get; set; }
        public DateTime DataVisita { get; set; }
        public StatusInteressadoEnum Status { get; set; }

        public Endereco Endereco { get; set; }
        public int EnderecoId { get; set; }

        public virtual ICollection<Produto> Produtos { get; set; }

    }
}

ProjIntegrador/Controllers/InteressadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjIntegrador.DataAccess;
using ProjIntegrador.Models;

namespace ProjIntegrador.Controllers
{
    public class InteressadoController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Interessado
        public ActionResult Index()
        {
            var interessado = db.Interessado.Include(i => i.Endereco);
            return View(interessado.ToList());
        }

        // GET: Interessado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interessado interessado = db.Interessado.Find(id);
            if (interessado == null)
            {
                return HttpNotFound();
            }
            return View(interessado);
        }

        // GET: Interessado/Create
        public ActionResult Create()
        {
            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao");
            return View();
        }

        // POST: Interessado/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InteressadoId,Nome,Telefone,Email,DataCadastro,DataAgendamento,DataVisita,Status,EnderecoId")] Interessado interessado)
        {
            if (ModelState.IsValid)
            {
                db.Interessado.Add(interessado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao", interessado.EnderecoId);
            return View(interessado);
        }

        // GET: Interessado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interessado interessado = db.Interessado.Find(id);
            if (interessado == null)
            {
                return HttpNotFound();
            }
            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao", interessado.EnderecoId);
            return View(interessado);
        }

        // POST: Interessado/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InteressadoId,Nome,Telefone,Email,DataCadastro,DataAgendamento,DataVisita,Status,EnderecoId")] Interessado interessado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(interessado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EnderecoId = new SelectList(db.Endereco, "EnderecoId", "Descricao", interessado.EnderecoId);
            return View(interessado);
        }

        // GET: Interessado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Interessado interessado = db.Interessado.Find(id);
            if (interessado == null)
            {
                return HttpNotFound();
            }
            return View(interessado);
        }

        // POST: Interessado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Interessado interessado = db.Interessado.Find(id);
            db.Interessado.Remove(interessado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjIntegrador/Views/Interessado/Create.cshtml
@model ProjIntegrador.Models.Interessado

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Interessados
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Interessado", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Cadastar novo Interessado
                    </div>
                    <br /><br />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class = "control-label col-md-2"> Data do Cadastro</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2"> Data do Agendamento</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DataAgendamento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DataAgendamento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2"> Data da Visita</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DataVisita, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DataVisita, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2">ID do Endereço</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.EnderecoId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EnderecoId, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-12">
                                <input type="submit" value="Criar Interessado" class="btn-wide btn btn-success mb-3" />
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Interessado/Delete.cshtml
@model ProjIntegrador.Models.Interessado

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Interessados
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Interessado", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Deletar Interessado
                    </div>
                    <br />

                    <div style="padding: 0 25px; margin: 10px 0;">
                        <div class="dl-horizontal">

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Nome)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Telefone)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Telefone)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Email)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Email)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    Data do Cadastro
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DataCadastro)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    Data do Agendamento
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DataAgendamento)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    Data da Visita
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DataVisita)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Status)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Status)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    ID do Endereço
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.EnderecoId)
                                </dd>
                            </div>

                        </div>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Deletar Interessado" class="btn-wide btn btn-success mb-3" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Interessado/Details.cshtml
@model ProjIntegrador.Models.Interessado

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Interessados
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Interessado", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Detalhes do Interessado
                    </div>

                    <div style="padding: 0 25px; margin: 10px 0;">
                        <div class="dl-horizontal">

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Nome)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Telefone)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Telefone)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Email)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Email)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    Data do Cadastro
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DataCadastro)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    Data do Agendamento
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DataAgendamento)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    Data da Visita
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.DataVisita)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Status)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Status)
                                </dd>
                            </div>

                            <div class="col-md-3">
                                <dt>
                                    ID do Endereço
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.EnderecoId)
                                </dd>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Interessado/Edit.cshtml
@model ProjIntegrador.Models.Interessado

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Interessados
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Interessado", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Editar Interessado
                    </div>
                    <br /><br />


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.InteressadoId)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2"> Data do Cadastro</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DataCadastro, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DataCadastro, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-12">
                                @Html.EnumDropDownListFor(model => model.Status, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2"> Data do Agendamento</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DataAgendamento, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DataAgendamento, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2"> Data da Visita</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DataVisita, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DataVisita, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="control-label col-md-2">ID do Endereço</div>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.EnderecoId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.EnderecoId, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Interessado/Index.cshtml
@model IEnumerable<ProjIntegrador.Models.Interessado>

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Interessados
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Criar Novo", "Create", "Interessado", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Interessados Cadastrados
                    </div>
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">Endereço</th>
                                    <th class="text-center">Nome</th>
                                    <th class="text-center">Telefone</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Cadastro</th>
                                    <th class="text-center">Agendamento</th>
                                    <th class="text-center">Visita</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Endereco.Descricao)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Nome)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Telefone)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.DataCadastro)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.DataAgendamento)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.DataVisita)
                                    </td>
                                    <td class="text-center">
                                        @Html.DisplayFor(modelItem => item.Status)
                                    </td>
                                    <td class="text-center">
                                        @Html.ActionLink("Edit", "Edit", new { id = item.InteressadoId }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.InteressadoId }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.InteressadoId })
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>