ProjIntegrador/Models/Instalador.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjIntegrador.Models
{
    public class Instalador
    {
        public int InstaladorId { get; set; }
        
        public Funcionario Funcionario { get; set; }
        public int FuncionarioId { get; set; }

        public virtual ICollection<Instalacao> Instalacoes { get; set; }
    }
}

ProjIntegrador/Controllers/InstaladorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjIntegrador.DataAccess;
using ProjIntegrador.Models;

namespace ProjIntegrador.Controllers
{
    public class InstaladorController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Instalador
        public ActionResult Index()
        {
            var instalador = db.Instalador.Include(i => i.Funcionario);
            return View(instalador.ToList());
        }

        // GET: Instalador/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalador instalador = db.Instalador.Find(id);
            if (instalador == null)
            {
                return HttpNotFound();
            }
            return View(instalador);
        }

        // GET: Instalador/Create
        public ActionResult Create()
        {
            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "FuncionarioId", "CPF");
            return View();
        }

        // POST: Instalador/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "InstaladorId,FuncionarioId")] Instalador instalador)
        {
            if (ModelState.IsValid)
            {
                db.Instalador.Add(instalador);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "FuncionarioId", "CPF", instalador.FuncionarioId);
            return View(instalador);
        }

        // GET: Instalador/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalador instalador = db.Instalador.Find(id);
            if (instalador == null)
            {
                return HttpNotFound();
            }
            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "FuncionarioId", "CPF", instalador.FuncionarioId);
            return View(instalador);
        }

        // POST: Instalador/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "InstaladorId,FuncionarioId")] Instalador instalador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(instalador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FuncionarioId = new SelectList(db.Funcionario, "FuncionarioId", "CPF", instalador.FuncionarioId);
            return View(instalador);
        }

        // GET: Instalador/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Instalador instalador = db.Instalador.Find(id);
            if (instalador == null)
            {
                return HttpNotFound();
            }
            return View(instalador);
        }

        // POST: Instalador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instalador instalador = db.Instalador.Find(id);
            db.Instalador.Remove(instalador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjIntegrador/Views/Instalador/Create.cshtml
@model ProjIntegrador.Models.Instalador

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalador
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalador", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Cadastar novo Instalador
                    </div>
                    <br /><br />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                <div class = "control-label col-md-2">ID do Funcionário</div>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.FuncionarioId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FuncionarioId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-12">
                                    <input type="submit" value="Criar Instalador" class="btn-wide btn btn-success mb-3" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalador/Delete.cshtml
@model ProjIntegrador.Models.Instalador

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalador
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalador", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Deletar Instalador
                    </div>
                    <br />

                    <div style="padding: 0 25px; margin: 10px 0;">
                        <div class="dl-horizontal">
                            <div class="col-md-3">
                                <dt>
                                    ID
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.InstaladorId)
                                </dd>
                            </div>
                        </div>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Deletar Instalador" class="btn-wide btn btn-success mb-3" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalador/Details.cshtml
@model ProjIntegrador.Models.Instalador

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalador
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalador", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Detalhes do Instalador
                    </div>

                    <div style="padding: 0 25px; margin: 10px 0;">
                        <div class="col-md-3">
                            <dt>
                                ID
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.InstaladorId)
                            </dd>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalador/Edit.cshtml
@model ProjIntegrador.Models.Instalador

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalador
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Voltar", "Index", "Instalador", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Editar Instalador
                    </div>
                    <br /><br />


                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.InstaladorId)
                            <div class="form-group">
                                <div class="control-label col-md-2">ID do Funcionário</div>
                                <div class="col-md-12">
                                    @Html.EditorFor(model => model.FuncionarioId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.FuncionarioId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-12">
                                    <input type="submit" value="Editar Instalador" class="btn-wide btn btn-success mb-3    " />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

ProjIntegrador/Views/Instalador/Index.cshtml
@model IEnumerable<ProjIntegrador.Models.Instalador>

<div class="app-main__outer">
    <div class="app-main__inner">
        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div>
                        Instalador
                        <div class="page-title-subheading">
                            This is an example dashboard created using build-in elements and components.
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.ActionLink("Criar Novo", "Create", "Instalador", null, new { @class = "btn-wide btn btn-success mb-3" })
            </div>
            <div class="col-md-12">
                <div class="main-card mb-3 card">
                    <div class="card-header">
                        Funcionários Cadastrados
                    </div>
                    <div class="table-responsive">
                        <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center">Id do Funcionário</th>
                                    <th class="text-center">Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="text-center">
                                            @Html.DisplayFor(modelItem => item.FuncionarioId)
                                        </td>
                                        <td class="text-center">
                                            @Html.ActionLink("Edit", "Edit", new { id = item.InstaladorId }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.InstaladorId }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.InstaladorId })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>